"""Archivist agent: generate CODEBASE.md and onboarding_brief.md from cartography artifacts."""

import json
from pathlib import Path
from typing import Any, Optional


def _load_json(path: Path) -> Optional[dict]:
    if not path.exists():
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def _generate_codebase_md(module_graph: dict, lineage_graph: dict) -> str:
    """Generate comprehensive CODEBASE.md from module and lineage graphs."""
    meta = module_graph.get("metadata") or {}
    repo = meta.get("repo_path", "repository")
    analyzed = meta.get("analyzed_at", "")
    files = meta.get("total_files", 0)
    langs = ", ".join(meta.get("languages_detected", []) or ["unknown"])

    lines = [
        "# CODEBASE — Living Map",
        "",
        f"**Generated by Brownfield Cartographer** · Repo: `{repo}` · Analyzed: {analyzed}",
        "",
        "---",
        "",
        "## Overview",
        "",
        f"- **Files analyzed:** {files}",
        f"- **Languages:** {langs}",
        f"- **Modules:** {len(module_graph.get('nodes', []))}",
        f"- **Datasets (lineage):** {len(lineage_graph.get('datasets', []))}",
        f"- **Transformations:** {len(lineage_graph.get('transformations', []))}",
        "",
        "---",
        "",
        "## Data Lineage",
        "",
    ]

    sources = lineage_graph.get("sources", [])
    sinks = lineage_graph.get("sinks", [])
    if sources:
        lines.append("### Data sources (entry points)")
        for s in sources[:20]:
            if not s.startswith("sql:"):
                lines.append(f"- `{s}`")
        lines.append("")
    if sinks:
        lines.append("### Data sinks (outputs)")
        for s in sinks[:20]:
            if not s.startswith("sql:"):
                lines.append(f"- `{s}`")
        lines.append("")

    critical = lineage_graph.get("critical_path", [])
    if critical:
        path_filtered = [n for n in critical if not n.startswith("sql:") or "models" in n]
        if path_filtered:
            lines.append("### Critical path (longest dependency chain)")
            lines.append("")
            lines.append("```")
            lines.append(" -> ".join(path_filtered[:12]))
            if len(path_filtered) > 12:
                lines.append(f" ... +{len(path_filtered) - 12} more")
            lines.append("```")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Module map (by domain)")

    nodes = module_graph.get("nodes", [])
    by_domain: dict[str, list[dict]] = {}
    for n in nodes:
        domain = (n.get("domain_cluster") or "uncategorized").strip()
        by_domain.setdefault(domain, []).append(n)

    for domain in sorted(by_domain.keys()):
        lines.append(f"### {domain}")
        lines.append("")
        for n in sorted(by_domain[domain], key=lambda x: x.get("path", "")):
            path = n.get("path", "")
            purpose = n.get("purpose_statement") or "(no description)"
            lang = n.get("language", "")
            loc = n.get("lines_of_code") or 0
            lines.append(f"- **`{path}`** ({lang}, {loc} LOC) — {purpose}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Hub modules (high PageRank)")
    hub = module_graph.get("hub_modules", [])[:15]
    if hub:
        for h in hub:
            lines.append(f"- `{h}`")
    else:
        lines.append("*None identified.*")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Regenerate with: `cartographer analyze <repo>`*")
    return "\n".join(lines)


def _generate_onboarding_brief(module_graph: dict, lineage_graph: dict) -> str:
    """Generate FDE onboarding quick-start guide."""
    meta = module_graph.get("metadata") or {}
    repo = meta.get("repo_path", "this repository")

    lines = [
        "# Onboarding Brief — FDE Day-One",
        "",
        f"**Target:** {repo}",
        "",
        "---",
        "",
        "## 1. What is the primary data ingestion path?",
        "",
    ]

    sources = lineage_graph.get("sources", [])
    sources_clean = [s for s in sources if not s.startswith("sql:")]
    if sources_clean:
        lines.append("Data enters via:")
        for s in sources_clean[:10]:
            lines.append(f"- **{s}**")
        lines.append("")
        lines.append("Staging/models consume these via `ref()` and `source()` (dbt) or equivalent.")
    else:
        lines.append("*(Run cartographer to populate.)*")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## 2. Critical output datasets")

    sinks = lineage_graph.get("sinks", [])
    sinks_clean = [s for s in sinks if not s.startswith("sql:")]
    if sinks_clean:
        for s in sinks_clean[:10]:
            lines.append(f"- **{s}**")
    else:
        lines.append("*(Run cartographer to populate.)*")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## 3. Blast radius (if a key module fails)")

    critical = lineage_graph.get("critical_path", [])
    if critical:
        lines.append("The longest dependency chain (critical path) is:")
        path_show = [n for n in critical if not n.startswith("sql:")][:8]
        lines.append("")
        lines.append(" -> ".join(path_show))
        lines.append("")
        lines.append("Failure of any node in this chain can block downstream nodes.")
    else:
        lines.append("*(Run cartographer to compute critical path.)*")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## 4. Where to start reading code")

    entry_points = module_graph.get("entry_points", [])
    hub = module_graph.get("hub_modules", [])[:5]
    if entry_points:
        lines.append("- **Entry points:** " + ", ".join(f"`{e}`" for e in entry_points[:5]))
    if hub:
        lines.append("- **Hub modules (high impact):** " + ", ".join(f"`{h}`" for h in hub))
    if not entry_points and not hub:
        lines.append("- Review **staging** and **marts** (or equivalent) in the module map in CODEBASE.md.")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## 5. Next steps")
    lines.append("")
    lines.append("1. Read **CODEBASE.md** for the full module map and lineage.")
    lines.append("2. Query the graph: `cartographer query <cartography_dir> <question>`")
    lines.append("3. Inspect `.cartography/module_graph.json` and `lineage_graph.json` for APIs.")
    return "\n".join(lines)


class Archivist:
    """Generates living documentation from cartography artifacts."""

    def __init__(self, cartography_dir: str | Path) -> None:
        self.cartography_dir = Path(cartography_dir)

    def generate_all(self) -> dict[str, str]:
        """Generate CODEBASE.md and onboarding_brief.md. Returns paths to written files."""
        module_path = self.cartography_dir / "module_graph.json"
        lineage_path = self.cartography_dir / "lineage_graph.json"

        module_graph = _load_json(module_path) or {"nodes": [], "metadata": {}}
        lineage_graph = _load_json(lineage_path) or {"datasets": [], "sources": [], "sinks": [], "critical_path": []}

        codebase_md = _generate_codebase_md(module_graph, lineage_graph)
        brief_md = _generate_onboarding_brief(module_graph, lineage_graph)

        codebase_path = self.cartography_dir / "CODEBASE.md"
        brief_path = self.cartography_dir / "onboarding_brief.md"

        codebase_path.write_text(codebase_md, encoding="utf-8")
        brief_path.write_text(brief_md, encoding="utf-8")

        return {"CODEBASE.md": str(codebase_path), "onboarding_brief.md": str(brief_path)}
